version: "3.9"

services:

  redis:
    image: redis/redis-stack:edge
    ports:
      - "6379:6379"
      - "8001:8001"
    environment:
      - "REDIS_ARGS=--appendonly yes --save 10 100"
      - "REDIS_PASSWORD=redis"
    volumes:
      - redis:/data
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
    healthcheck:
      test: [ "CMD", "redis-cli", "--raw", "incr", "ping" ]
      interval: 1s
      timeout: 10s
      retries: 20
      start_period: 3s


  grafana:
    image: grafana/grafana:9.1.2
    ports:
      - "3000:3000"
    # we need `dns` to dial external hosts, e.g., storage.googleapis.com
    dns:
      - 8.8.8.8
    environment:
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_BASIC_ENABLED=false
      - GF_ENABLE_GZIP=true
      - GF_USERS_DEFAULT_THEME=dark
      - GF_INSTALL_PLUGINS=redis-datasource,redis-app
      # defend following secrets in .env and don't commit `.env` file to git.
      - REDIS_CLOUD_HOST
      - REDIS_CLOUD_PASSWORD
    volumes:
      - ./grafana/provisioning/datasources/:/etc/grafana/provisioning/datasources/:ro
      - ./grafana/provisioning/dashboards/:/etc/grafana/provisioning/dashboards/:ro
      - grafana:/var/lib/grafana
    links:
      - redis
    depends_on:
      redis:
        condition: service_healthy

volumes:
  redis:
  grafana: